# Generated by Django 4.2.3 on 2023-07-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularcarmodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='popularcarmodel',
            name='topic',
        ),
        migrations.AddField(
            model_name='popularcarmodel',
            name='carname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popularcarmodel',
            name='image',
            field=models.FileField(default=1, upload_to='mainapp/static'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popularcarmodel',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
