# Generated by Django 4.2.3 on 2023-08-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_popularcarmodel_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='justlaunchedmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='mainapp/static')),
                ('carname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
