# Generated by Django 4.2.3 on 2023-08-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_upcomingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='happycoustmermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='mainapp/static')),
                ('carname', models.CharField(max_length=30)),
                ('comments', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
