# Generated by Django 4.2.3 on 2023-08-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_carstockmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='cargalerymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='mainapp/static')),
                ('carname', models.CharField(max_length=30)),
            ],
        ),
    ]
