# Generated by Django 4.2.3 on 2023-08-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_regmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('newsid', models.IntegerField()),
                ('image', models.FileField(upload_to='mainapp/static')),
                ('carname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('offerprice', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
