# Generated by Django 4.2.3 on 2023-08-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_wishmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishmodel',
            name='totalprice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
