# Generated by Django 4.2.3 on 2023-08-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_wishmodel_totalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='buymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalamount', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='wishmodel',
            name='totalprice',
        ),
    ]
