# Generated by Django 4.2.3 on 2023-08-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_carstockmodel_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carstockmodel',
            name='seat',
            field=models.IntegerField(),
        ),
    ]
