# Generated by Django 4.2.3 on 2023-08-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_carstockmodel_imagee_carstockmodel_imageee'),
    ]

    operations = [
        migrations.AddField(
            model_name='regmodel',
            name='balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
