# Generated by Django 4.2.3 on 2023-08-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_withmoney'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buymodel',
            old_name='totalamount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='buymodel',
            name='carname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
