# Generated by Django 4.2.3 on 2023-08-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_rename_totalamount_buymodel_price_buymodel_carname'),
    ]

    operations = [
        migrations.AddField(
            model_name='buymodel',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
